/*
 * generated by Xtext
 */
package uniandes.academia;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GeneratorRuntimeModule extends uniandes.academia.AbstractGeneratorRuntimeModule {

}
