/*
* generated by Xtext
*/
package uniandes.academia;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GeneratorStandaloneSetup extends GeneratorStandaloneSetupGenerated{

	public static void doSetup() {
		new GeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

