/*
 * generated by Xtext
 */
package uniandes.academia.ui.contentassist

import uniandes.academia.ui.contentassist.AbstractGeneratorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GeneratorProposalProvider extends AbstractGeneratorProposalProvider {
}
