/*
 * generated by Xtext
 */
package uniandes.academia.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GeneratorUiModule extends uniandes.academia.ui.AbstractGeneratorUiModule {
	public GeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
